env:
  browser: true
  commonjs: true
  es2021: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 12
rules: 
  indent: ['error', 2, { SwitchCase: 1 }]
  quotes: ['error', 'single']
  semi: ['error', 'never']
  # 烦死了
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
globals:
  mw: writeable